
# Netlify configuration file
[build]
  publish = "dist"
  command = "echo 'Using pre-built files'"

# Optional: Configure redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
