// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tundfobzusqdsmiskssc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1bmRmb2J6dXNxZHNtaXNrc3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDMyODMsImV4cCI6MjA2MDYxOTI4M30.0qzswdUmZmncYUsHYMkjBgM0wtwLp2Ruge9ryBEXQc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);